FROM ubuntu:16.04 AS build-env

RUN apt update && apt install -y \
    git \
    build-essential \
    make

RUN git clone https://github.com/jeansimeoni/daitan-university-c-devenv-sample-1.git /tmp/myapp
WORKDIR /tmp/myapp
RUN ls

RUN make

FROM ubuntu:16.04

RUN apt-get update && apt-get upgrade -y

ENTRYPOINT ["/usr/bin/app"]

COPY --from=build-env /tmp/myapp/build/bin/app /usr/bin
